// This file is generated by Firebase Extensions.
'use server';
/**
 * @fileOverview Explains an ingredient from a food product.
 *
 * - explainIngredient - A function that handles the ingredient explanation process.
 * - ExplainIngredientInput - The input type for the explainIngredient function.
 * - ExplainIngredientOutput - The return type for the explainIngredient function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainIngredientInputSchema = z.object({
  ingredientName: z.string().describe('The name of the ingredient to explain.'),
  productName: z.string().describe('The name of the food product the ingredient is in.'),
});
export type ExplainIngredientInput = z.infer<typeof ExplainIngredientInputSchema>;

const ExplainIngredientOutputSchema = z.object({
  explanation: z.string().describe('An explanation of what the ingredient is and why it is used in the product.'),
});
export type ExplainIngredientOutput = z.infer<typeof ExplainIngredientOutputSchema>;

export async function explainIngredient(input: ExplainIngredientInput): Promise<ExplainIngredientOutput> {
  return explainIngredientFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainIngredientPrompt',
  input: {schema: ExplainIngredientInputSchema},
  output: {schema: ExplainIngredientOutputSchema},
  prompt: `You are an expert in food science and nutrition.

You will receive the name of an ingredient and the name of a food product.

Your task is to explain what the ingredient is and why it is used in the product.

Ingredient Name: {{{ingredientName}}}
Product Name: {{{productName}}}

Explanation: `,
});

const explainIngredientFlow = ai.defineFlow(
  {
    name: 'explainIngredientFlow',
    inputSchema: ExplainIngredientInputSchema,
    outputSchema: ExplainIngredientOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
