// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides a recommendation of whether the user should consume the product.
 *
 * - recommendProduct - A function that provides recommendation of whether the user should consume the product.
 * - RecommendProductInput - The input type for the recommendProduct function.
 * - RecommendProductOutput - The return type for the recommendProduct function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendProductInputSchema = z.object({
  ingredients: z.string().describe('The list of ingredients in the product.'),
  healthRating: z
    .string()
    .describe("The health rating of the product (A-F)."
    ),
});
export type RecommendProductInput = z.infer<typeof RecommendProductInputSchema>;

const RecommendProductOutputSchema = z.object({
  recommendation: z
    .enum(['Yes', 'No', 'Caution'])
    .describe('The recommendation of whether the user should consume the product.'),
  explanation: z.string().describe('The explanation for the recommendation.'),
});
export type RecommendProductOutput = z.infer<typeof RecommendProductOutputSchema>;

export async function recommendProduct(input: RecommendProductInput): Promise<RecommendProductOutput> {
  return recommendProductFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendProductPrompt',
  input: {schema: RecommendProductInputSchema},
  output: {schema: RecommendProductOutputSchema},
  prompt: `You are an AI assistant that provides a recommendation of whether the user should consume the product.

  Given the following ingredients and health rating, provide a recommendation of whether the user should consume the product.

  Ingredients: {{{ingredients}}}
  Health Rating: {{{healthRating}}}

  Your response should include a recommendation (Yes, No, or Caution) and a brief explanation for the recommendation.
`,
});

const recommendProductFlow = ai.defineFlow(
  {
    name: 'recommendProductFlow',
    inputSchema: RecommendProductInputSchema,
    outputSchema: RecommendProductOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
